server:
  port: 0
  
spring:
  application:
    name: customer-service
    
  data:
    mongodb:
      uri: mongodb://localhost:27017/banca

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    
  server:
    wait-time-in-ms-when-sync-empty: 0
    
#spring:
#  application:
#    name: customer-service
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/banca
#  cloud:
#    config:
#      uri: http://localhost:8888
#  autoconfigure:
#      exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#management:
#  security:
#    enabled: false